sn1124
bug-zero/bz_org_logo pull request #23
Opened 2019-12-29 23:03 UTC by samaynandwana

sn1124's bug zero logo design

2019-12-30 12:31 UTC, jakubpawlina requested changes
You should add these files to the directory created by you, named with your GCI name, not to the main directory.

2019-12-31 18:51 UTC, jakubpawlina approved these changes
Now it seems to be ok for me

2020-01-01 01:34 UTC, Niweera approved these changes

2020-01-03 11:22 UTC, thisuraseniya approved these changes

2020-01-03 11:22 UTC, merged